# Dockerfile
FROM python:3.11-slim
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y build-essential libpq-dev curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -r requirements.txt


COPY . .
# If you use collectstatic, set STATIC_ROOT in settings and keep this:
RUN python manage.py collectstatic --noinput || true

EXPOSE 8000
CMD ["gunicorn", "watch-shop-app/WatchShop/WatchShop/wsgi.py/wsgi:application", "--bind", "0.0.0.0:8000"]


