FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y build-essential libpq-dev curl && rm -rf /var/lib/apt/lists/*

# install python deps
COPY requirements.txt .
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*


# copy your whole repo
COPY . .

# collect static using the correct manage.py location
RUN python watch-shop-app/manage.py collectstatic --noinput || true

EXPOSE 8000

# IMPORTANT: use module import path, not a filesystem path.
# We cd into the folder that contains the inner `WatchShop/` package,
# then load the WSGI app.
gunicorn --chdir watch-shop-app/WatchShop WatchShop.wsgi:application --bind 0.0.0.0:8000




