apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchshop
  namespace: watchshop
  labels:
    app: watchshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watchshop
  template:
    metadata:
      labels:
        app: watchshop
    spec:
      containers:
        - name: web
          image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/watchshop:latest  # Jenkins replaces this
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
