apiVersion: v1
kind: Service
metadata:
  name: watch-shop-service
spec:
  type: NodePort
  selector:
    app: watch-shop
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
